// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EFCoreDateTime.DbModel
{
    public partial class DateTimeTest
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime dt1 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime dt2 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime dt3 { get; set; }
        public DateTimeOffset dfoff1 { get; set; }
        public DateTimeOffset dfoff2 { get; set; }
        public DateTimeOffset dfoff3 { get; set; }
        public DateTimeOffset dfoffMSKDateTime { get; set; }
    }
}